### ISSUE TITLE
The `pfire --help` example in the documentation says "not found"

### ISSUE THREAD

**Issue by drj11** [INSIGNEO/pFIRE#48]
As of writing, in the documentation https://insigneo.github.io/pFIRE/cli_quickstart.html#elastic-registration

says

```
pFIRE is invoked from the console:

$ pfire --help
bash: line 1: pfire: command not found
```

I'm pretty sure that it should show an example output from the `pfire` command, instead of `pfire: command not found`.

**Comment by ptooley** [comment]
Ah, this is due to the documentation output being dynamically generated, paths clearly need to be fixed in the script...
